apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - k8s.local
    secretName: test-cluster-cert
  rules:
  - http:
      paths:
      - path: /test-cluster
        pathType: Prefix
        backend:
          service:
            name: test-cluster
            port:
              number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: test-cluster
  namespace: default
spec:
  selector:
    name: test-cluster
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cluster
spec:
  selector:
    matchLabels:
      name: test-cluster
  replicas: 2
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /test
      labels:
        name: test-cluster
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
